#!/bin/bash

#server="10.2.9.97"
#server="10.2.10.144"
server="192.168.19.1"
lftp << EOF
open $server
lcd release
echo "sync to $server..."
mirror -R javascripts
mirror -R stylesheets
mirror -R template
mirror -R images
mirror -R partials
put index.html
EOF
echo "done."
